const KEY='macTrackerShifts_wow_v1';
let shifts=JSON.parse(localStorage.getItem(KEY)||'[]');
const nlMonths={januari:0,februari:1,maart:2,april:3,mei:4,juni:5,juli:6,augustus:7,september:8,oktober:9,november:10,december:11};
function $(id){return document.getElementById(id)}
function save(msg='Opgeslagen'){localStorage.setItem(KEY,JSON.stringify(shifts));render();showToast(msg)}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function pad(n){return String(n).padStart(2,'0')}
function fmtDate(d){return new Date(d+'T12:00:00').toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'})}
function minutesBetween(date,start,end,brk=0){if(!date||!start||!end)return 0;let s=new Date(`${date}T${start}`),e=new Date(`${date}T${end}`);if(e<=s)e.setDate(e.getDate()+1);return Math.max(0,((e-s)/60000)-Number(brk||0))}
function hoursText(mins){return (Math.round((mins/60)*10)/10)+'h'}
function money(v){return '€'+Math.round(v)}
function addShift(){const shift={id:Date.now()+Math.random(),date:$('date').value,start:$('start').value,end:$('end').value,break:Number($('break').value||0),position:$('position').value.trim()||'Shift',rate:Number($('rate').value||0),note:$('note').value.trim()};if(!shift.date||!shift.start||!shift.end){showToast('Vul datum, start en einde in');return}shifts.push(shift);shifts.sort((a,b)=>new Date(a.date)-new Date(b.date));$('position').value='';$('note').value='';save('Dienst toegevoegd')}
function del(id){shifts=shifts.filter(s=>s.id!==id);save('Dienst verwijderd')}
function clearAll(){if(confirm('Alles wissen?')){shifts=[];save('Alles gewist')}}
function getWeekNumber(d){d=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));let y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}
function render(){const now=new Date(),thisMonth=now.getMonth(),thisYear=now.getFullYear(),thisWeek=getWeekNumber(now);let weekM=0,monthM=0,weekC=0,monthC=0,earned=0,next=null;const q=($('search')?.value||'').toLowerCase();$('list').innerHTML='';shifts.forEach(s=>{const d=new Date(s.date+'T12:00:00'),mins=minutesBetween(s.date,s.start,s.end,s.break);if(d.getFullYear()===thisYear&&getWeekNumber(d)===thisWeek){weekM+=mins;weekC++}if(d.getFullYear()===thisYear&&d.getMonth()===thisMonth){monthM+=mins;monthC++;earned+=(mins/60)*Number(s.rate||0)}if(new Date(`${s.date}T${s.start}`)>=now&&(!next||new Date(`${s.date}T${s.start}`)<new Date(`${next.date}T${next.start}`)))next=s});weekHours.textContent=hoursText(weekM);weekCount.textContent=weekC+' diensten';monthHours.textContent=hoursText(monthM);monthCount.textContent=monthC+' diensten';earned.textContent=money(earned);monthBar.style.width=Math.min(100,(monthM/(120*60))*100)+'%';if(next){nextShift.textContent=fmtDate(next.date);nextInfo.textContent=next.start+' - '+next.end}else{nextShift.textContent='–';nextInfo.textContent='niets gepland'}const filtered=shifts.filter(s=>(s.position+' '+(s.note||'')).toLowerCase().includes(q));if(!filtered.length){$('list').innerHTML='<div class="empty">Nog geen diensten gevonden.</div>';return}filtered.slice().reverse().forEach(s=>{const mins=minutesBetween(s.date,s.start,s.end,s.break);const div=document.createElement('div');div.className='shift';div.innerHTML=`<div><strong>${fmtDate(s.date)} · ${s.start} - ${s.end}</strong><small>${s.position}${s.note?' · '+s.note:''}</small><span class="pill">⏱ ${hoursText(mins)}</span><span class="pill">☕ pauze ${s.break||0} min</span><span class="pill">💸 ${money((mins/60)*Number(s.rate||0))}</span></div><button class="secondary" onclick="del(${s.id})">Delete</button>`;$('list').appendChild(div)})}
function parseDutchDate(txt){txt=txt.toLowerCase().replace(/,/g,' ');const m=txt.match(/(\d{1,2})\s+(januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december)\s+(20\d{2})/i);if(!m)return null;return `${m[3]}-${pad(nlMonths[m[2]]+1)}-${pad(m[1])}`}
function importShifts(){const lines=$('importText').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);let added=0;lines.forEach(line=>{const d=parseDutchDate(line),t=line.match(/(\d{1,2}:\d{2})\s*-\s*(\d{1,2}:\d{2})/);if(d&&t){let after=line.split(t[0])[1]||'';let pos=after.replace(/^[,\s-]+/,'').trim()||'Imported shift';shifts.push({id:Date.now()+Math.random(),date:d,start:t[1],end:t[2],break:30,position:pos,rate:Number($('rate').value||12.41),note:'Imported'});added++}});if(!added){showToast('Geen shifts gevonden');alert('Geen shifts gevonden. Probeer: vrijdag 17 juli 2026 20:30 - 02:30, MPS');return}$('importText').value='';shifts.sort((a,b)=>new Date(a.date)-new Date(b.date));save(added+' shift(s) geïmporteerd')}
function exportData(){const blob=new Blob([JSON.stringify(shifts,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mac-tracker-backup.json';a.click();URL.revokeObjectURL(a.href);showToast('Backup gedownload')}
function fillDemo(){const today=new Date();const d=`${today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}`;$('date').value=d;$('start').value='17:30';$('end').value='01:30';$('break').value='30';$('position').value='MPS Close';$('note').value='Demo shift'}
function tick(){const n=new Date();clock.textContent=n.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});todayLine.textContent=n.getHours()<12?'Goedemorgen, Hamed ☀️':n.getHours()<18?'Ready voor vandaag ⚡':'Avond shift mode 🌙'}
(function init(){const t=new Date();$('date').value=`${t.getFullYear()}-${pad(t.getMonth()+1)}-${pad(t.getDate())}`;tick();setInterval(tick,1000);render()})();
